# Generated by Django 4.1.2 on 2022-11-05 21:42

from django.db import migrations
import systems.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='environment',
            field=systems.models.fields.EncryptedDataField(default={}),
        ),
    ]
