# Generated by Django 4.1.2 on 2022-11-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_alter_group_secrets'),
        ('platform', '0003_platform_config_platform_provider_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='%(data_name)s', to='group.group'),
        ),
    ]
