_base_model: &base_model
    base: name_resource
    admin_roles: [ platform-admin ]
    view_roles: [ platform-auditor ]
    priority: 60

roles:
    platform-admin: Platform administrator (full privileges over all platforms)
    platform-auditor: Platform auditor (viewing privileges over all platforms)

models:
    platform:
        <<: *base_model
        mixins: [ group ]
        plugin: true
        display: "<name>"
        priority: 65
        fields:
            remote:
                type: string
            reference:
                type: string
            environment:
                type: encrypted_dict
            state:
                type: encrypted_text
                options:
                    editable: false
