config:
    name: null # REQUIRED
    provider: terraform
    fields: {}
    active: true
    development: false

    zimagi_version: main

    platform_private_key: null
    platform_public_key: null

run:
    "deploy_@name":
        _command: platform save
        platform_key: "@name"
        platform_provider_name: "@provider"
        platform_fields: "@fields"

destroy:
    "destroy_@name":
        _command: platform remove
        platform_key: "@name"
